server:
  port: 8084

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
  sql:
    init:
      mode: always
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      connection-timeout: 20000
#      maximumPoolSize: 5
#      minimum-idle: 5
#      idle-timeout: 10000
#      max-lifetime: 1800000
#      auto-commit: true

tenants:
  datasources:
    public:
      jdbcUrl: jdbc:postgresql://localhost:5432/public
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: password
    tenant_1:
      jdbcUrl: jdbc:postgresql://localhost:5432/tenant_1
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: password
    tenant_2:
      jdbcUrl: jdbc:postgresql://localhost:5432/tenant_2
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: password