server:
  port: 8084

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

tenants:
  datasources:
    read:
      jdbcUrl: jdbc:postgresql://localhost:5432/read
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: password
    write:
      jdbcUrl: jdbc:postgresql://localhost:5432/write
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: password