server:
  port: 8084

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    
tenants:
  datasources:
    tenant_1:
      jdbcUrl: jdbc:postgresql://localhost:5432/tenant_1
      driver-class-name: org.postgresql.Driver
      username: postgres
    tenant_2:
      jdbcUrl: jdbc:postgresql://localhost:5432/tenant_2
      driver-class-name: org.postgresql.Driver
      username: postgres
